Repository Kernel360/E2E2-SPEECH-UP, pull requests merged in 2024-08, with the labels that each got.

#34 [#33] 외부 API 요청
  .gitignore
  .idea/.gitignore
  build.gradle
  src/main/java/com/speech/up/UpApplication.java
  src/main/java/com/speech/up/api/voiceToText/TestController.java
  src/main/java/com/speech/up/api/voiceToText/etri/dto/RequestVoiceToTextApiDTO.java
  src/main/java/com/speech/up/api/voiceToText/etri/dto/ResponseVoiceToTextApiDTO.java
  src/main/java/com/speech/up/api/voiceToText/etri/service/VoiceToTextService.java
  src/main/java/com/speech/up/api/voiceToText/speechFlow/service/VoiceToTextSpeechFlowService.java
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/test/java/com/speech/up/api/voiceToText/VoiceToTextTest.java
Labels: enhancement

#63 [#61] 사용자 정보 세션 저장 기능 구현
  src/main/java/com/speech/up/oAuth/filter/JwtAuthenticationFilter.java
  src/main/java/com/speech/up/oAuth/handler/OAuth2SuccessHandler.java
  src/main/java/com/speech/up/oAuth/service/implement/OAuth2UserServiceImplement.java
  src/main/java/com/speech/up/oAuth/service/implement/OAuthServiceImplement.java
  src/main/java/com/speech/up/script/controller/ScriptController.java
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
  src/main/resources/static/scriptPage/js/scriptList.js
  src/main/resources/templates/home.html
Labels: enhancement

#79 Feature/#76/report
  src/main/java/com/speech/up/report/controller/ReportController.java
  src/main/java/com/speech/up/report/entity/BaseReportEntity.java
  src/main/java/com/speech/up/report/entity/ReportEntity.java
  src/main/java/com/speech/up/report/entity/type/ReportContentAndScore.java
  src/main/java/com/speech/up/report/repository/ReportRepository.java
  src/main/java/com/speech/up/report/service/ReportService.java
  src/main/java/com/speech/up/report/service/dto/ReportAddDto.java
Labels: enhancement

#77 [#76] Report 기능 일부 구현
  src/main/java/com/speech/up/report/controller/ReportController.java
  src/main/java/com/speech/up/report/entity/BaseReportEntity.java
  src/main/java/com/speech/up/report/entity/ReportEntity.java
  src/main/java/com/speech/up/report/entity/type/ReportContentAndScore.java
  src/main/java/com/speech/up/report/repository/ReportRepository.java
  src/main/java/com/speech/up/report/service/ReportService.java
  src/main/java/com/speech/up/report/service/dto/ReportAddDto.java
Labels: enhancement

#80 [#76] Etri AI 요청 기능 추가
  build/resources/main/application.yaml
  src/main/java/com/speech/up/UpApplication.java
  src/main/java/com/speech/up/api/etri/controller/TestController.java
  src/main/java/com/speech/up/api/etri/dto/RequestVoiceToTextApiDto.java
  src/main/java/com/speech/up/api/etri/dto/ResponseVoiceToTextApiDto.java
  src/main/java/com/speech/up/api/etri/service/ApiType.java
  src/main/java/com/speech/up/api/etri/service/ApiUrl.java
  src/main/java/com/speech/up/api/etri/service/PronunciationAI.java
  src/main/java/com/speech/up/api/etri/service/RecognizedAI.java
  src/main/java/com/speech/up/api/etri/service/UrlCollector.java
  src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
  src/main/resources/application.yaml
Labels: enhancement

#81 [#76] Etri AI 요청 기능 추가 - body 수정
  src/main/java/com/speech/up/api/etri/controller/TestController.java
  src/main/java/com/speech/up/api/etri/dto/AiRequest.java
  src/main/java/com/speech/up/api/etri/dto/RequestVoiceToTextApiDto.java
  src/main/java/com/speech/up/api/etri/dto/ResponseVoiceToTextApiDto.java
  src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
Labels: enhancement

#83 [#82] 녹음 추가
  src/main/resources/static/css/record-style.css
  src/main/resources/static/scriptPage/js/addRecordingToList.js
  src/main/resources/static/scriptPage/js/record.js
  src/main/resources/static/scriptPage/js/saveRecord.js
  src/main/resources/templates/script.html
Labels: enhancement

#85 [#55] OAuth session 제거
  src/main/java/com/speech/up/api/speechFlow/service/VoiceToTextSpeechFlowService.java
  src/main/java/com/speech/up/demo/HomePageController.java
  src/main/java/com/speech/up/demo/ScriptPageController.java
  src/main/java/com/speech/up/oAuth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/oAuth/filter/JwtAuthenticationFilter.java
  src/main/java/com/speech/up/oAuth/handler/OAuth2SuccessHandler.java
  src/main/java/com/speech/up/oAuth/service/implement/OAuth2UserServiceImplement.java
  src/main/java/com/speech/up/script/controller/ScriptController.java
  src/main/java/com/speech/up/script/service/ScriptService.java
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
  src/main/resources/static/scriptPage/js/addTokenSession.js
  src/main/resources/static/scriptPage/js/scriptList.js
  src/main/resources/static/scriptPage/js/scriptWrite.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/home.html
  src/main/resources/templates/script-list.html
  src/main/resources/templates/script-write.html
Labels: enhancement

#86 [#82] feature : wav to raw, 변환 후 api 호출 기능
  build.gradle
  src/main/java/com/speech/up/api/converter/WavToRaw.java
  src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
  src/test/java/com/speech/up/script/service/ScriptServiceTest.java
Labels: enhancement

#87 [#55] OAuth 카카오, 깃허브 로그인 추가
  build/resources/main/application.yaml
  src/main/java/com/speech/up/UpApplication.java
  src/main/java/com/speech/up/api/etri/dto/AiRequest.java
  src/main/java/com/speech/up/api/etri/service/ApiType.java
  src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
  src/main/java/com/speech/up/api/etri/type/ApiType.java
  src/main/java/com/speech/up/api/etri/url/ApiUrl.java
  src/main/java/com/speech/up/api/etri/url/PronunciationAI.java
  src/main/java/com/speech/up/api/etri/url/RecognizedAI.java
  src/main/java/com/speech/up/api/etri/url/UrlCollector.java
  src/main/java/com/speech/up/oAuth/entity/CustomOAuth2User.java
  src/main/java/com/speech/up/oAuth/provider/GithubProvider.java
  src/main/java/com/speech/up/oAuth/provider/GoogleProvider.java
  src/main/java/com/speech/up/oAuth/provider/KakaoProvider.java
  src/main/java/com/speech/up/oAuth/provider/Provider.java
  src/main/java/com/speech/up/oAuth/provider/ProviderOAuth.java
  src/main/java/com/speech/up/oAuth/service/implement/OAuth2UserServiceImplement.java
  src/main/java/com/speech/up/oAuth/service/implement/UserAuthorizationType.java
  src/main/java/com/speech/up/oAuth/service/servicetype/LevelType.java
  src/main/java/com/speech/up/oAuth/service/servicetype/ProviderType.java
  src/main/resources/application.yaml
Labels: enhancement

#89 [#88] exception 수정
  src/main/java/com/speech/up/api/speechFlow/controller/SpeechFlowAPIController.java
  src/main/java/com/speech/up/api/speechFlow/service/VoiceToTextSpeechFlowService.java
  src/main/java/com/speech/up/common/dto/ApiExceptionResponse.java
  src/main/java/com/speech/up/common/enums/StatusCode.java
  src/main/java/com/speech/up/common/exception/custom/CustomIOException.java
  src/main/java/com/speech/up/common/exception/custom/CustomIllegalArgumentException.java
  src/main/java/com/speech/up/common/exception/custom/CustomRuntimeException.java
  src/main/java/com/speech/up/common/exception/handler/ExceptionController.java
  src/main/java/com/speech/up/common/exception/http/BadRequestException.java
  src/main/java/com/speech/up/common/exception/http/ForbiddenException.java
  src/main/java/com/speech/up/common/exception/http/HttpBaseException.java
  src/main/java/com/speech/up/common/exception/http/InternalServerErrorException.java
  src/main/java/com/speech/up/common/exception/http/NotFoundException.java
  src/main/java/com/speech/up/common/exception/http/UnAuthorizedException.java
  src/main/java/com/speech/up/customException/ResponseContentIsNullException.java
  src/main/java/com/speech/up/customException/TaskIdIsNullException.java
  src/main/java/com/speech/up/globalException/ErrorResponse.java
  src/main/java/com/speech/up/globalException/GlobalException.java
  src/main/java/com/speech/up/script/controller/RecordController.java
  src/main/java/com/speech/up/script/service/ScriptService.java
Labels: enhancement

#90 [#69] board pagination 검색 기능 추가
  src/main/java/com/speech/up/board/controller/BoardController.java
  src/main/java/com/speech/up/board/entity/BoardEntity.java
  src/main/java/com/speech/up/board/repository/BoardRepository.java
  src/main/java/com/speech/up/board/service/BoardService.java
  src/main/java/com/speech/up/board/service/checkValue/CheckListForPagination.java
  src/main/java/com/speech/up/board/service/checkValue/CheckParamForPagination.java
  src/main/java/com/speech/up/board/service/dto/BoardGetDto.java
  src/main/java/com/speech/up/board/service/dto/BoardIsUseDto.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
Labels: enhancement

#92 [#72] 게시판 기능 프론트
  src/main/java/com/speech/up/board/controller/BoardController.java
  src/main/java/com/speech/up/board/repository/BoardRepository.java
  src/main/java/com/speech/up/board/service/BoardService.java
  src/main/java/com/speech/up/board/service/dto/BoardGetDto.java
  src/main/java/com/speech/up/demo/BoardPageController.java
  src/main/java/com/speech/up/oAuth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/user/repository/UserRepository.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/resources/static/css/board-write.css
  src/main/resources/static/css/header-style.css
  src/main/resources/static/css/home-style.css
  src/main/resources/static/css/script-style.css
  src/main/resources/static/scriptPage/js/boardModify.js
  src/main/resources/static/scriptPage/js/checkBoardOwner.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/board-detail.html
  src/main/resources/templates/board-write.html
  src/main/resources/templates/board.html
  src/main/resources/templates/home.html
  src/main/resources/templates/script-list.html
  src/main/resources/templates/script-write.html
  src/main/resources/templates/script.html
  src/main/resources/templates/signIn.html
Labels: enhancement

#93 [#82] feature : 업로드 된 파일 데이터로 API 요청 및 오류 수정
  build/resources/main/application.yaml
  src/main/java/com/speech/up/api/converter/WavToRaw.java
  src/main/java/com/speech/up/api/etri/controller/ETRIApiController.java
  src/main/java/com/speech/up/api/etri/controller/TestController.java
  src/main/java/com/speech/up/api/etri/dto/AiRequest.java
  src/main/java/com/speech/up/api/etri/dto/RequestVoiceToTextApiDto.java
  src/main/java/com/speech/up/api/etri/service/VoiceToTextService.java
  src/main/java/com/speech/up/api/etri/url/UrlCollector.java
  src/main/java/com/speech/up/oAuth/config/WebSecurityConfig.java
  src/main/resources/application.yaml
  src/main/resources/static/scriptPage/js/saveRecord.js
  src/main/resources/static/scriptPage/js/scriptDetail.js
  src/main/resources/templates/script.html
Labels: enhancement

#94 [#91] feature : 커스텀 로그 일부 추가
  src/main/java/com/speech/up/board/service/BoardService.java
  src/main/java/com/speech/up/log/CustomLogger.java
  src/main/java/com/speech/up/script/service/RecordService.java
  src/main/java/com/speech/up/script/service/ScriptService.java
  src/main/resources/application.yaml
Labels: enhancement

#96 [#84] feature : 리플 CRUD 추가
  src/main/java/com/speech/up/reply/controller/ReplyController.java
  src/main/java/com/speech/up/reply/entity/ReplyBaseEntity.java
  src/main/java/com/speech/up/reply/entity/ReplyEntity.java
  src/main/java/com/speech/up/reply/repository/ReplyRepository.java
  src/main/java/com/speech/up/reply/service/ReplyService.java
  src/main/java/com/speech/up/reply/service/dto/ReplyAddDto.java
  src/main/java/com/speech/up/reply/service/dto/ReplyGetDto.java
  src/main/java/com/speech/up/reply/service/dto/ReplyIsUseDto.java
  src/main/java/com/speech/up/reply/service/dto/ReplyUpdateDto.java
Labels: enhancement

#100 [#72] 자유게시판 기능 구현, 댓글 추가
  src/main/java/com/speech/up/reply/controller/ReplyController.java
  src/main/java/com/speech/up/reply/entity/ReplyEntity.java
  src/main/java/com/speech/up/reply/repository/ReplyRepository.java
  src/main/java/com/speech/up/reply/service/ReplyService.java
  src/main/java/com/speech/up/reply/service/dto/ReplyGetDto.java
  src/main/resources/static/scriptPage/js/reply.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/board-detail.html
Labels: enhancement

#103 [#102] 마이페이지 프론트, 회원 탈퇴 기능 구현
  src/main/java/com/speech/up/demo/HomePageController.java
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/repository/UserRepository.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
  src/main/resources/static/css/my-page.css
  src/main/resources/static/scriptPage/js/userDelete.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/myPage.html
Labels: enhancement

#104 [#102] 각 페이지 갯수 가져오기
  src/main/java/com/speech/up/board/controller/BoardController.java
  src/main/java/com/speech/up/board/repository/BoardRepository.java
  src/main/java/com/speech/up/board/service/BoardService.java
  src/main/java/com/speech/up/demo/BoardPageController.java
  src/main/java/com/speech/up/reply/controller/ReplyController.java
  src/main/java/com/speech/up/reply/repository/ReplyRepository.java
  src/main/java/com/speech/up/reply/service/ReplyService.java
  src/main/java/com/speech/up/script/controller/ScriptController.java
  src/main/java/com/speech/up/script/repository/ScriptRepository.java
  src/main/java/com/speech/up/script/service/ScriptService.java
  src/main/resources/static/css/header-style.css
  src/main/resources/static/css/land-style.css
  src/main/resources/static/scriptPage/js/boardCount.js
  src/main/resources/static/scriptPage/js/reply.js
  src/main/resources/static/scriptPage/js/replyCount.js
  src/main/resources/static/scriptPage/js/scriptCount.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/home.html
  src/main/resources/templates/myPage.html
Labels: enhancement

#105 [#102] 커스텀 로그 변경
  src/main/java/com/speech/up/auth/common/ResponseCode.java
  src/main/java/com/speech/up/auth/common/ResponseMessage.java
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/auth/entity/CustomOAuth2User.java
  src/main/java/com/speech/up/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/speech/up/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/speech/up/auth/provider/GithubProvider.java
  src/main/java/com/speech/up/auth/provider/GoogleProvider.java
  src/main/java/com/speech/up/auth/provider/JwtProvider.java
  src/main/java/com/speech/up/auth/provider/KakaoProvider.java
  src/main/java/com/speech/up/auth/provider/Provider.java
  src/main/java/com/speech/up/auth/provider/ProviderOAuth.java
  src/main/java/com/speech/up/auth/service/implement/OAuth2UserServiceImplement.java
  src/main/java/com/speech/up/auth/service/implement/UserAuthorizationType.java
  src/main/java/com/speech/up/auth/service/servicetype/LevelType.java
  src/main/java/com/speech/up/auth/service/servicetype/ProviderType.java
  src/main/java/com/speech/up/board/service/BoardService.java
  src/main/java/com/speech/up/log/CustomLogger.java
  src/main/java/com/speech/up/record/service/RecordService.java
  src/main/java/com/speech/up/reply/service/ReplyService.java
  src/main/java/com/speech/up/script/service/ScriptService.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/resources/application.yaml
Labels: enhancement

#108 [#107] feature : Script 테스트 코드 추가
  src/test/java/com/speech/up/script/service/ScriptServiceTest.java
Labels: enhancement

#112 [#111] 배포 테스트
  build.gradle
  gradlew
  src/main/java/com/speech/up/UpApplication.java
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/speech/up/auth/provider/KakaoProvider.java
  src/main/java/com/speech/up/script/service/dto/ScriptIsUseDto.java
  src/main/java/com/speech/up/script/service/dto/ScriptUpdateDto.java
  src/main/resources/application.yaml
  src/test/java/com/speech/up/script/entity/ScriptEntityTest.java
  src/test/java/com/speech/up/script/repository/ScriptRepositoryTest.java
  src/test/java/com/speech/up/user/controller/UserControllerTest.java
  src/test/java/com/speech/up/user/entity/UserEntityTest.java
  src/test/java/com/speech/up/user/service/UserServiceTest.java
Labels: documentation, enhancement, good first issue

#133 [#127] feature : kakaoMap Api를 이용한 주변 학원 탐색 페이지 및 기능 추가
  README.md
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/demo/HomePageController.java
  src/main/java/com/speech/up/report/repository/ReportRepository.java
  src/main/java/com/speech/up/report/service/ReportService.java
  src/main/resources/static/css/kakaomap-style.css
  src/main/resources/static/scriptPage/js/analyticRecord.js
  src/main/resources/static/scriptPage/js/map.js
  src/main/resources/templates/home.html
  src/main/resources/templates/map.html
Labels: enhancement

#140 [#139] 장기 미접속 유저 삭제
  src/main/java/com/speech/up/auth/service/implement/OAuth2UserServiceImplement.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
  src/main/java/com/speech/up/user/repository/UserRepository.java
  src/main/java/com/speech/up/user/service/UserScheduling.java
Labels: documentation

#142 [#113] Authorization 사용 부분 수정
  src/main/java/com/speech/up/admin/controller/AdminController.java
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/speech/up/board/controller/BoardController.java
  src/main/java/com/speech/up/record/controller/RecordController.java
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
  src/main/resources/static/scriptPage/js/analyticRecord.js
  src/main/resources/static/scriptPage/js/boardModify.js
  src/main/resources/static/scriptPage/js/boardWrite.js
  src/main/resources/static/scriptPage/js/checkBoardOwner.js
  src/main/resources/static/scriptPage/js/checkLogined.js
  src/main/resources/static/scriptPage/js/loadLocalRecord.js
  src/main/resources/static/scriptPage/js/myPage.js
  src/main/resources/static/scriptPage/js/saveRecord.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/myPage.html
  src/main/resources/templates/script.html
Labels: documentation, enhancement

#145 스케쥴러 일부 추가
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
  src/main/java/com/speech/up/user/repository/UserRepository.java
  src/main/java/com/speech/up/user/service/UserScheduling.java
  src/main/java/com/speech/up/user/service/UserService.java
Labels: enhancement

#147 [#146]관리자 페이지 구현 완료
  src/main/java/com/speech/up/admin/controller/AdminController.java
  src/main/java/com/speech/up/admin/controller/AdminPageController.java
  src/main/java/com/speech/up/auth/provider/GithubProvider.java
  src/main/java/com/speech/up/auth/provider/GoogleProvider.java
  src/main/java/com/speech/up/auth/provider/KakaoProvider.java
  src/main/java/com/speech/up/auth/service/implement/UserAuthorizationType.java
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/repository/UserRepository.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/java/com/speech/up/user/service/dto/UserGetInfoDto.java
  src/main/resources/static/css/admin-view.css
  src/main/resources/static/scriptPage/js/adminUserHandler.js
  src/main/resources/static/scriptPage/js/checkAdministration.js
  src/main/resources/templates/admin-page.html
Labels: enhancement

#150 [#127] 스피치 학원 없을 경우 페이지를 닫는 코드 추가
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/resources/static/scriptPage/js/map.js
  src/main/resources/static/scriptPage/js/userMe.js
  src/main/resources/templates/myPage.html
Labels: enhancement

#152 [#151] javadoc 작성
  build.gradle
  src/main/java/com/speech/up/board/controller/BoardController.java
  src/main/java/com/speech/up/demo/BoardPageController.java
  src/main/java/com/speech/up/demo/HomePageController.java
  src/main/java/com/speech/up/demo/RegisterPageController.java
  src/main/java/com/speech/up/demo/ReportPageController.java
  src/main/java/com/speech/up/demo/ScriptPageController.java
  src/main/java/com/speech/up/record/controller/RecordController.java
  src/main/java/com/speech/up/reply/controller/ReplyController.java
  src/main/java/com/speech/up/user/controller/UserController.java
Labels: enhancement

#154 [#153] 데이터 통계 리포트
  src/main/java/com/speech/up/admin/controller/AdminController.java
  src/main/java/com/speech/up/admin/controller/OpenDataController.java
  src/main/java/com/speech/up/admin/dto/StatisticsAdd.java
  src/main/java/com/speech/up/admin/dto/StatisticsGet.java
  src/main/java/com/speech/up/admin/entity/StatisticsEntity.java
  src/main/java/com/speech/up/admin/repository/StatisticsRepository.java
  src/main/java/com/speech/up/admin/service/StatisticsScheduling.java
  src/main/java/com/speech/up/admin/service/StatisticsService.java
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/report/entity/dto/ReportGetDto.java
  src/main/java/com/speech/up/report/repository/ReportRepository.java
  src/test/java/com/speech/up/report/service/ReportService.java
Labels: enhancement

#158 [#157] 테스트 코드 추가
  src/main/java/com/speech/up/reply/controller/ReplyController.java
  src/main/java/com/speech/up/reply/service/ReplyService.java
  src/test/java/com/speech/up/board/service/BoardServiceTest.java
  src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
  src/test/java/com/speech/up/script/service/ScriptServiceTest.java
Labels: enhancement

#163 [#54] report 서비스 테스트 코드
  build.gradle
  src/main/java/com/speech/up/report/repository/ReportRepository.java
  src/main/java/com/speech/up/report/service/ReportService.java
  src/test/java/com/speech/up/board/service/BoardServiceTest.java
  src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
  src/test/java/com/speech/up/report/repository/ReportRepositoryTest.java
  src/test/java/com/speech/up/report/service/ReportService.java
  src/test/java/com/speech/up/report/service/ReportServiceTest.java
Labels: enhancement

#166 [#54] 레포지토리 테스트 추가
  src/main/java/com/speech/up/board/service/checkValue/CheckListForPagination.java
  src/test/java/com/speech/up/board/repository/BoardRepositoryTest.java
  src/test/java/com/speech/up/board/service/BoardServiceTest.java
  src/test/java/com/speech/up/record/repository/RecordRepositoryTest.java
  src/test/java/com/speech/up/record/service/RecordServiceTest.java
  src/test/java/com/speech/up/reply/repository/ReplyRepositoryTest.java
  src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
  src/test/java/com/speech/up/report/service/ReportServiceTest.java
  src/test/java/com/speech/up/script/repository/ScriptRepositoryTest.java
  src/test/java/com/speech/up/script/service/ScriptServiceTest.java
  src/test/java/com/speech/up/user/repositiory/UserRepositoryTest.java
  src/test/java/com/speech/up/user/service/UserServiceTest.java
Labels: enhancement

#177 Refector/user
  src/main/java/com/speech/up/auth/provider/GithubProvider.java
  src/main/java/com/speech/up/auth/provider/GoogleProvider.java
  src/main/java/com/speech/up/auth/provider/KakaoProvider.java
  src/main/java/com/speech/up/auth/service/implement/OAuth2UserServiceImplement.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
  src/main/resources/static/css/board-style.css
  src/main/resources/static/js/boardWrite.js
  src/main/resources/templates/board-write.html
  src/main/resources/templates/board.html
Labels: enhancement

#181 [#180] feature : 오디오 파일 체크 추가
  src/main/resources/templates/board.html
  src/main/resources/templates/script.html
Labels: enhancement

#172 [#54] 테스트 코드 추가
  build.gradle
  src/main/java/com/speech/up/reply/controller/ReplyController.java
  src/main/resources/application-test.yaml
  src/test/java/com/speech/up/UpApplicationTests.java
  src/test/java/com/speech/up/board/controller/BoardControllerTest.java
  src/test/java/com/speech/up/board/service/BoardServiceTest.java
  src/test/java/com/speech/up/record/controller/RecordControllerTest.java
  src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
  src/test/java/com/speech/up/report/controller/ReportControllerTest.java
  src/test/java/com/speech/up/report/repository/ReportRepositoryTest.java
  src/test/java/com/speech/up/report/service/ReportServiceTest.java
  src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
  src/test/java/com/speech/up/script/service/ScriptServiceTest.java
  src/test/java/com/speech/up/user/controller/UserControllerTest.java
  src/test/java/com/speech/up/user/repositiory/UserRepositoryTest.java
  src/test/java/com/speech/up/user/service/UserServiceTest.java
Labels: enhancement

#185 [#54] coverage 를 위한 테스트 코드 수정
  src/test/java/com/speech/up/admin/service/StatisticsSchedulingTest.java
  src/test/java/com/speech/up/admin/service/StatisticsServiceTest.java
  src/test/java/com/speech/up/board/controller/BoardControllerTest.java
  src/test/java/com/speech/up/record/controller/RecordControllerTest.java
  src/test/java/com/speech/up/record/service/RecordServiceTest.java
  src/test/java/com/speech/up/user/service/UserServiceTest.java
Labels: enhancement

#188 [#189] 테스트 코드 추가
  src/test/java/com/speech/up/auth/provider/GithubProviderTest.java
  src/test/java/com/speech/up/auth/provider/GoogleProviderTest.java
  src/test/java/com/speech/up/auth/provider/JwtProviderTest.java
  src/test/java/com/speech/up/auth/provider/KakaoProviderTest.java
  src/test/java/com/speech/up/auth/provider/ProviderTest.java
Labels: enhancement

#187 [#54] coverage 를 위한 테스트 코드 수정
  src/main/java/com/speech/up/api/etri/controller/ETRIApiController.java
  src/main/java/com/speech/up/api/etri/dto/RequestPronunciationDto.java
  src/main/java/com/speech/up/api/etri/dto/ResponsePronunciationApiDto.java
  src/main/java/com/speech/up/api/etri/dto/ResponseRecognitionDto.java
  src/main/java/com/speech/up/report/entity/dto/ReportGetDto.java
  src/test/java/com/speech/up/admin/controller/AdminControllerTest.java
  src/test/java/com/speech/up/admin/controller/AdminPageControllerTest.java
  src/test/java/com/speech/up/admin/controller/OpenDataControllerTest.java
  src/test/java/com/speech/up/api/etri/controller/ETRIApiControllerTest.java
  src/test/java/com/speech/up/api/etri/dto/RequestPronunciationDtoTest.java
  src/test/java/com/speech/up/api/etri/dto/RequestRecognitionDtoTest.java
  src/test/java/com/speech/up/api/etri/dto/ResponsePronunciationApiDtoTest.java
  src/test/java/com/speech/up/api/etri/dto/ResponseRecognitionDto.java
  src/test/java/com/speech/up/api/etri/type/ApiTypeTest.java
  src/test/java/com/speech/up/api/etri/url/PronunciationAITest.java
  src/test/java/com/speech/up/api/etri/url/RecognizedAITest.java
  src/test/java/com/speech/up/api/etri/url/UrlCollectorTest.java
  src/test/java/com/speech/up/common/enums/StatusCodeTest.java
  src/test/java/com/speech/up/common/exception/custom/CustomIOExceptionTest.java
  src/test/java/com/speech/up/common/exception/custom/CustomIllegalArgumentExceptionTest.java
  src/test/java/com/speech/up/common/exception/custom/CustomRuntimeExceptionTest.java
  src/test/java/com/speech/up/common/exception/http/ForbiddenExceptionTest.java
  src/test/java/com/speech/up/common/exception/http/InternalServerErrorExceptionTest.java
  src/test/java/com/speech/up/common/exception/http/NotFoundExceptionTest.java
  src/test/java/com/speech/up/common/exception/http/UnAuthorizedExceptionTest.java
  src/test/java/com/speech/up/record/service/dto/RecordAddDtoTest.java
  src/test/java/com/speech/up/record/service/dto/RecordIsUseDtoTest.java
  src/test/java/com/speech/up/reply/controller/ReplyControllerTest.java
  src/test/java/com/speech/up/reply/entity/ReplyBaseEntityTest.java
  src/test/java/com/speech/up/report/controller/ReportControllerTest.java
  src/test/java/com/speech/up/report/entity/dto/ReportGetDtoTest.java
  src/test/java/com/speech/up/report/repository/ReportRepositoryTest.java
  src/test/java/com/speech/up/report/service/ReportServiceTest.java
  src/test/java/com/speech/up/script/controller/ScriptControllerTest.java
  src/test/java/com/speech/up/user/controller/UserControllerTest.java
  src/test/java/com/speech/up/user/service/UserSchedulingTest.java
Labels: enhancement

#190 [#54] feat: demo test code
  build.gradle
  src/test/java/com/speech/up/demo/BoardPageControllerTest.java
  src/test/java/com/speech/up/demo/HomePageControllerTest.java
  src/test/java/com/speech/up/demo/RegisterPageControllerTest.java
  src/test/java/com/speech/up/demo/ReportPageControllerTest.java
  src/test/java/com/speech/up/demo/ScriptPageControllerTest.java
Labels: enhancement

#192 [#54] coverage 를 위한 테스트 코드 수정
  src/test/java/com/speech/up/auth/entity/CustomOAuth2UserTest.java
  src/test/java/com/speech/up/auth/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/speech/up/auth/handler/OAuth2SuccessHandlerTest.java
  src/test/java/com/speech/up/reply/service/ReplyServiceTest.java
Labels: enhancement

#194 [#54] env 관련 테스트 수정
  .gitignore
  src/test/java/com/speech/up/UpApplicationTests.java
Labels: bug, enhancement

#196 [#54] env 관련 테스트 수정
  src/test/java/com/speech/up/UpApplicationTests.java
  src/test/java/com/speech/up/demo/HomePageControllerTest.java
Labels: bug, enhancement

#202 [#169] 밴 사용자 적용
  src/main/java/com/speech/up/admin/entity/StatisticsEntity.java
  src/main/java/com/speech/up/auth/config/WebSecurityConfig.java
  src/main/java/com/speech/up/auth/provider/GithubProvider.java
  src/main/java/com/speech/up/auth/provider/GoogleProvider.java
  src/main/java/com/speech/up/auth/provider/KakaoProvider.java
  src/main/java/com/speech/up/auth/service/implement/UserAuthorizationType.java
  src/main/java/com/speech/up/common/enums/UserStatusCode.java
  src/main/java/com/speech/up/demo/BannedController.java
  src/main/java/com/speech/up/user/controller/UserController.java
  src/main/java/com/speech/up/user/entity/UserEntity.java
  src/main/java/com/speech/up/user/repository/UserRepository.java
  src/main/java/com/speech/up/user/service/UserService.java
  src/main/java/com/speech/up/user/service/dto/UserUpdateDto.java
  src/main/resources/static/js/checkBanned.js
  src/main/resources/static/js/userMe.js
  src/main/resources/templates/banned.html
  src/test/java/com/speech/up/auth/provider/GithubProviderTest.java
  src/test/java/com/speech/up/auth/provider/GoogleProviderTest.java
  src/test/java/com/speech/up/auth/provider/KakaoProviderTest.java
  src/test/java/com/speech/up/demo/BannedControllerTest.java
  src/test/java/com/speech/up/user/controller/UserControllerTest.java
  src/test/java/com/speech/up/user/service/UserServiceTest.java
Labels: enhancement

#210 [#169] 테스트 코드 수정, 미사용 코드 삭제
  src/main/java/com/speech/up/api/etri/dto/AiRequest.java
  src/main/java/com/speech/up/auth/handler/OAuth2SuccessHandler.java
  src/test/java/com/speech/up/common/aspect/LoggingAspectTest.java
Labels: enhancement

#215 [#214] docs : 주석 추가
  src/main/java/com/speech/up/admin/controller/AdminPageController.java
  src/main/java/com/speech/up/demo/BannedController.java
Labels: documentation
